// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sogou/speech/asr/v1/asr.proto

package asr

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	longrunning "golang.speech.sogou.com/apis/longrunning"
	status "google.golang.org/genproto/googleapis/rpc/status"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status1 "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Audio encoding of the data sent in the audio message. All encodings support
// only 1 channel (mono) audio. Only `FLAC` include a header that
// describes the bytes of audio that follow the header. The other encodings
// are raw audio bytes with no header.
//
// For best results, the audio source should be captured and transmitted using
// a lossless encoding (`FLAC` or `LINEAR16`). Recognition accuracy may be
// reduced if lossy codecs, which include the other codecs listed in
// this section, are used to capture or transmit the audio, particularly if
// background noise is present.
type RecognitionConfig_AudioEncoding int32

const (
	// Not specified. Will return result status 400.
	RecognitionConfig_ENCODING_UNSPECIFIED RecognitionConfig_AudioEncoding = 0
	// Uncompressed 16-bit signed little-endian samples (Linear PCM).
	// `sample_rate_hertz` must be 16000.
	// (when language-code = zh-cmn-Hans-CN and model = phonecall, it must be 8000)
	RecognitionConfig_LINEAR16 RecognitionConfig_AudioEncoding = 1
	// [`FLAC`](https://xiph.org/flac/documentation.html) (Free Lossless Audio
	// Codec) is the recommended encoding because it is
	// lossless--therefore recognition is not compromised--and
	// requires only about half the bandwidth of `LINEAR16`. `FLAC` stream
	// encoding only supports 16-bit samples, however, not all fields in
	// `STREAMINFO` are supported.
	// `sample_rate_hertz` must be 16000.
	// (when language-code = zh-cmn-Hans-CN and model = phonecall, it must be 8000)
	RecognitionConfig_FLAC RecognitionConfig_AudioEncoding = 2
	// Opus encoded audio frames in Ogg container
	// ([OggOpus](https://wiki.xiph.org/OggOpus)).
	// `sample_rate_hertz` must be one of 8000, 12000, 16000, 24000, or 48000.
	RecognitionConfig_OGG_OPUS RecognitionConfig_AudioEncoding = 6
	// Raw opus format
	// 16-bit big endian integer n follows n bytes opus frame
	// `sample_rate_hertz` must be 16000.
	RecognitionConfig_OPUS_WITH_HEADER RecognitionConfig_AudioEncoding = 7
	// Sogou specific speex format 16-bit samples 1 channel
	RecognitionConfig_SOGOU_SPEEX RecognitionConfig_AudioEncoding = 100
)

var RecognitionConfig_AudioEncoding_name = map[int32]string{
	0:   "ENCODING_UNSPECIFIED",
	1:   "LINEAR16",
	2:   "FLAC",
	6:   "OGG_OPUS",
	7:   "OPUS_WITH_HEADER",
	100: "SOGOU_SPEEX",
}

var RecognitionConfig_AudioEncoding_value = map[string]int32{
	"ENCODING_UNSPECIFIED": 0,
	"LINEAR16":             1,
	"FLAC":                 2,
	"OGG_OPUS":             6,
	"OPUS_WITH_HEADER":     7,
	"SOGOU_SPEEX":          100,
}

func (x RecognitionConfig_AudioEncoding) String() string {
	return proto.EnumName(RecognitionConfig_AudioEncoding_name, int32(x))
}

func (RecognitionConfig_AudioEncoding) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{4, 0}
}

// Enumerates the types of capture settings describing an audio file.
type RecognitionMetadata_MicrophoneDistance int32

const (
	// Audio type is not known.
	RecognitionMetadata_MICROPHONE_DISTANCE_UNSPECIFIED RecognitionMetadata_MicrophoneDistance = 0
	// The audio was captured from a closely placed microphone. Eg. phone,
	// dictaphone, or handheld microphone. Generally if there speaker is within
	// 1 meter of the microphone.
	RecognitionMetadata_NEARFIELD RecognitionMetadata_MicrophoneDistance = 100
	// The speaker if within 3 meters of the microphone.
	RecognitionMetadata_MIDFIELD RecognitionMetadata_MicrophoneDistance = 300
	// The speaker is more than 3 meters away from the microphone.
	RecognitionMetadata_FARFIELD RecognitionMetadata_MicrophoneDistance = 500
)

var RecognitionMetadata_MicrophoneDistance_name = map[int32]string{
	0:   "MICROPHONE_DISTANCE_UNSPECIFIED",
	100: "NEARFIELD",
	300: "MIDFIELD",
	500: "FARFIELD",
}

var RecognitionMetadata_MicrophoneDistance_value = map[string]int32{
	"MICROPHONE_DISTANCE_UNSPECIFIED": 0,
	"NEARFIELD":                       100,
	"MIDFIELD":                        300,
	"FARFIELD":                        500,
}

func (x RecognitionMetadata_MicrophoneDistance) String() string {
	return proto.EnumName(RecognitionMetadata_MicrophoneDistance_name, int32(x))
}

func (RecognitionMetadata_MicrophoneDistance) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{5, 0}
}

// Indicates the type of speech event.
type StreamingRecognizeResponse_SpeechEventType int32

const (
	// No speech event specified.
	StreamingRecognizeResponse_SPEECH_EVENT_UNSPECIFIED StreamingRecognizeResponse_SpeechEventType = 0
	// This event indicates that the server has detected the end of the user's
	// speech utterance and expects no additional speech. Therefore, the server
	// will not process additional audio (although it may subsequently return
	// additional results). The client should stop sending additional audio
	// data, half-close the gRPC connection, and wait for any additional results
	// until the server closes the gRPC connection. This event is only sent if
	// `single_utterance` was set to `true`, and is not used otherwise.
	StreamingRecognizeResponse_END_OF_SINGLE_UTTERANCE StreamingRecognizeResponse_SpeechEventType = 1
)

var StreamingRecognizeResponse_SpeechEventType_name = map[int32]string{
	0: "SPEECH_EVENT_UNSPECIFIED",
	1: "END_OF_SINGLE_UTTERANCE",
}

var StreamingRecognizeResponse_SpeechEventType_value = map[string]int32{
	"SPEECH_EVENT_UNSPECIFIED": 0,
	"END_OF_SINGLE_UTTERANCE":  1,
}

func (x StreamingRecognizeResponse_SpeechEventType) String() string {
	return proto.EnumName(StreamingRecognizeResponse_SpeechEventType_name, int32(x))
}

func (StreamingRecognizeResponse_SpeechEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{11, 0}
}

// The top-level message sent by the client for the `Recognize` method.
type RecognizeRequest struct {
	// *Required* Provides information to the recognizer that specifies how to
	// process the request.
	Config *RecognitionConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// *Required* The audio data to be recognized.
	Audio                *RecognitionAudio `protobuf:"bytes,2,opt,name=audio,proto3" json:"audio,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RecognizeRequest) Reset()         { *m = RecognizeRequest{} }
func (m *RecognizeRequest) String() string { return proto.CompactTextString(m) }
func (*RecognizeRequest) ProtoMessage()    {}
func (*RecognizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{0}
}

func (m *RecognizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognizeRequest.Unmarshal(m, b)
}
func (m *RecognizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognizeRequest.Marshal(b, m, deterministic)
}
func (m *RecognizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognizeRequest.Merge(m, src)
}
func (m *RecognizeRequest) XXX_Size() int {
	return xxx_messageInfo_RecognizeRequest.Size(m)
}
func (m *RecognizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecognizeRequest proto.InternalMessageInfo

func (m *RecognizeRequest) GetConfig() *RecognitionConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *RecognizeRequest) GetAudio() *RecognitionAudio {
	if m != nil {
		return m.Audio
	}
	return nil
}

// The top-level message sent by the client for the `LongRunningRecognize`
// method.
type LongRunningRecognizeRequest struct {
	// *Required* Provides information to the recognizer that specifies how to
	// process the request.
	Config *RecognitionConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// *Required* The audio data to be recognized.
	Audio                *RecognitionAudio `protobuf:"bytes,2,opt,name=audio,proto3" json:"audio,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LongRunningRecognizeRequest) Reset()         { *m = LongRunningRecognizeRequest{} }
func (m *LongRunningRecognizeRequest) String() string { return proto.CompactTextString(m) }
func (*LongRunningRecognizeRequest) ProtoMessage()    {}
func (*LongRunningRecognizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{1}
}

func (m *LongRunningRecognizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongRunningRecognizeRequest.Unmarshal(m, b)
}
func (m *LongRunningRecognizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongRunningRecognizeRequest.Marshal(b, m, deterministic)
}
func (m *LongRunningRecognizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongRunningRecognizeRequest.Merge(m, src)
}
func (m *LongRunningRecognizeRequest) XXX_Size() int {
	return xxx_messageInfo_LongRunningRecognizeRequest.Size(m)
}
func (m *LongRunningRecognizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LongRunningRecognizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LongRunningRecognizeRequest proto.InternalMessageInfo

func (m *LongRunningRecognizeRequest) GetConfig() *RecognitionConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *LongRunningRecognizeRequest) GetAudio() *RecognitionAudio {
	if m != nil {
		return m.Audio
	}
	return nil
}

// The top-level message sent by the client for the `StreamingRecognize` method.
// Multiple `StreamingRecognizeRequest` messages are sent. The first message
// must contain a `streaming_config` message and must not contain `audio` data.
// All subsequent messages must contain `audio` data and must not contain a
// `streaming_config` message.
type StreamingRecognizeRequest struct {
	// The streaming request, which is either a streaming config or audio content.
	//
	// Types that are valid to be assigned to StreamingRequest:
	//	*StreamingRecognizeRequest_StreamingConfig
	//	*StreamingRecognizeRequest_AudioContent
	StreamingRequest     isStreamingRecognizeRequest_StreamingRequest `protobuf_oneof:"streaming_request"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *StreamingRecognizeRequest) Reset()         { *m = StreamingRecognizeRequest{} }
func (m *StreamingRecognizeRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRecognizeRequest) ProtoMessage()    {}
func (*StreamingRecognizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{2}
}

func (m *StreamingRecognizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRecognizeRequest.Unmarshal(m, b)
}
func (m *StreamingRecognizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRecognizeRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRecognizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRecognizeRequest.Merge(m, src)
}
func (m *StreamingRecognizeRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRecognizeRequest.Size(m)
}
func (m *StreamingRecognizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRecognizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRecognizeRequest proto.InternalMessageInfo

type isStreamingRecognizeRequest_StreamingRequest interface {
	isStreamingRecognizeRequest_StreamingRequest()
}

type StreamingRecognizeRequest_StreamingConfig struct {
	StreamingConfig *StreamingRecognitionConfig `protobuf:"bytes,1,opt,name=streaming_config,json=streamingConfig,proto3,oneof"`
}

type StreamingRecognizeRequest_AudioContent struct {
	AudioContent []byte `protobuf:"bytes,2,opt,name=audio_content,json=audioContent,proto3,oneof"`
}

func (*StreamingRecognizeRequest_StreamingConfig) isStreamingRecognizeRequest_StreamingRequest() {}

func (*StreamingRecognizeRequest_AudioContent) isStreamingRecognizeRequest_StreamingRequest() {}

func (m *StreamingRecognizeRequest) GetStreamingRequest() isStreamingRecognizeRequest_StreamingRequest {
	if m != nil {
		return m.StreamingRequest
	}
	return nil
}

func (m *StreamingRecognizeRequest) GetStreamingConfig() *StreamingRecognitionConfig {
	if x, ok := m.GetStreamingRequest().(*StreamingRecognizeRequest_StreamingConfig); ok {
		return x.StreamingConfig
	}
	return nil
}

func (m *StreamingRecognizeRequest) GetAudioContent() []byte {
	if x, ok := m.GetStreamingRequest().(*StreamingRecognizeRequest_AudioContent); ok {
		return x.AudioContent
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamingRecognizeRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamingRecognizeRequest_StreamingConfig)(nil),
		(*StreamingRecognizeRequest_AudioContent)(nil),
	}
}

// Provides information to the recognizer that specifies how to process the
// request.
type StreamingRecognitionConfig struct {
	// *Required* Provides information to the recognizer that specifies how to
	// process the request.
	Config *RecognitionConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// *Optional* If `false` or omitted, the recognizer will perform continuous
	// recognition (continuing to wait for and process audio even if the user
	// pauses speaking) until the client closes the input stream (gRPC API) or
	// until the maximum time limit has been reached. May return multiple
	// `StreamingRecognitionResult`s with the `is_final` flag set to `true`.
	//
	// If `true`, the recognizer will detect a single spoken utterance. When it
	// detects that the user has paused or stopped speaking, it will return an
	// `END_OF_SINGLE_UTTERANCE` event and cease recognition. It will return no
	// more than one `StreamingRecognitionResult` with the `is_final` flag set to
	// `true`.
	SingleUtterance bool `protobuf:"varint,2,opt,name=single_utterance,json=singleUtterance,proto3" json:"single_utterance,omitempty"`
	// *Optional* If `true`, interim results (tentative hypotheses) may be
	// returned as they become available (these interim results are indicated with
	// the `is_final=false` flag).
	// If `false` or omitted, only `is_final=true` result(s) are returned.
	InterimResults bool `protobuf:"varint,3,opt,name=interim_results,json=interimResults,proto3" json:"interim_results,omitempty"`
	// *Optional* If `true`, adds punctuation to interim recognition result hypotheses.
	// available only if RecognitionConfig.disable_automatic_punctuation = false AND interim_results = true
	//
	// NOTE: deprecated
	EnableInterimResultsPunctuation bool `protobuf:"varint,4,opt,name=enable_interim_results_punctuation,json=enableInterimResultsPunctuation,proto3" json:"enable_interim_results_punctuation,omitempty"`
	// *Optional* similar to `single_utterance`. But if `true`,
	// the recognizer will NOT detect any single spoken utterance
	// until the client closes the input stream (gRPC API) or
	// until the maximum time limit has been reached (approximately 30 seconds).
	// It will return only one `StreamingRecognitionResult`s with the `is_final` set to `true`.
	MergeUtterance       bool     `protobuf:"varint,5,opt,name=merge_utterance,json=mergeUtterance,proto3" json:"merge_utterance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRecognitionConfig) Reset()         { *m = StreamingRecognitionConfig{} }
func (m *StreamingRecognitionConfig) String() string { return proto.CompactTextString(m) }
func (*StreamingRecognitionConfig) ProtoMessage()    {}
func (*StreamingRecognitionConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{3}
}

func (m *StreamingRecognitionConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRecognitionConfig.Unmarshal(m, b)
}
func (m *StreamingRecognitionConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRecognitionConfig.Marshal(b, m, deterministic)
}
func (m *StreamingRecognitionConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRecognitionConfig.Merge(m, src)
}
func (m *StreamingRecognitionConfig) XXX_Size() int {
	return xxx_messageInfo_StreamingRecognitionConfig.Size(m)
}
func (m *StreamingRecognitionConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRecognitionConfig.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRecognitionConfig proto.InternalMessageInfo

func (m *StreamingRecognitionConfig) GetConfig() *RecognitionConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *StreamingRecognitionConfig) GetSingleUtterance() bool {
	if m != nil {
		return m.SingleUtterance
	}
	return false
}

func (m *StreamingRecognitionConfig) GetInterimResults() bool {
	if m != nil {
		return m.InterimResults
	}
	return false
}

func (m *StreamingRecognitionConfig) GetEnableInterimResultsPunctuation() bool {
	if m != nil {
		return m.EnableInterimResultsPunctuation
	}
	return false
}

func (m *StreamingRecognitionConfig) GetMergeUtterance() bool {
	if m != nil {
		return m.MergeUtterance
	}
	return false
}

// Provides information to the recognizer that specifies how to process the
// request.
type RecognitionConfig struct {
	// *Required* Encoding of audio data sent in all `RecognitionAudio` messages.
	Encoding RecognitionConfig_AudioEncoding `protobuf:"varint,1,opt,name=encoding,proto3,enum=sogou.speech.asr.v1.RecognitionConfig_AudioEncoding" json:"encoding,omitempty"`
	// *Required* Sample rate in Hertz of the audio data sent in all
	// `RecognitionAudio` messages.
	// In most cases, it should be specified as 16000.
	SampleRateHertz int32 `protobuf:"varint,2,opt,name=sample_rate_hertz,json=sampleRateHertz,proto3" json:"sample_rate_hertz,omitempty"`
	// *Required* The language code of the supplied audio.
	// Example: "zh-cmn-Hans-CN".
	// See [Language Support](https://zhiyin.sogou.com/doc/?url=/docs/content/asr/concepts/lauguages/) for a list of the currently supported language codes.
	LanguageCode string `protobuf:"bytes,3,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	// *Optional* Maximum number of recognition hypotheses to be returned.
	// Specifically, the maximum number of `SpeechRecognitionAlternative` messages
	// within each `SpeechRecognitionResult`.
	// The server may return fewer than `max_alternatives`.
	// Valid values are `0`-`5`. A value of `0` or `1` will return 1.
	// If omitted, will return 1.
	MaxAlternatives int32 `protobuf:"varint,4,opt,name=max_alternatives,json=maxAlternatives,proto3" json:"max_alternatives,omitempty"`
	// *Optional* If set to `true`, the server will attempt to filter out
	// profanities
	ProfanityFilter bool `protobuf:"varint,5,opt,name=profanity_filter,json=profanityFilter,proto3" json:"profanity_filter,omitempty"`
	// *Optional* A means to provide context to assist the speech recognition.
	SpeechContexts []*SpeechContext `protobuf:"bytes,6,rep,name=speech_contexts,json=speechContexts,proto3" json:"speech_contexts,omitempty"`
	// *Optional* If `true`, the top result includes a list of words and
	// the start and end time offsets (timestamps) for those words. If
	// `false`, no word-level time offset information is returned. The default is
	// `false`.
	EnableWordTimeOffsets bool `protobuf:"varint,8,opt,name=enable_word_time_offsets,json=enableWordTimeOffsets,proto3" json:"enable_word_time_offsets,omitempty"`
	// *Optional* Metadata regarding this request.
	Metadata *RecognitionMetadata `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// *Optional* If 'true', stop adds punctuation to recognition result hypotheses.
	// The default 'false' value DOES add punctuation to result hypotheses.
	DisableAutomaticPunctuation bool `protobuf:"varint,11,opt,name=disable_automatic_punctuation,json=disableAutomaticPunctuation,proto3" json:"disable_automatic_punctuation,omitempty"`
	// *Optional* Which model to select for the given request. Select the model
	// best suited to your domain to get best results. If a model is not
	// explicitly specified, "default" model is used.
	Model                string   `protobuf:"bytes,13,opt,name=model,proto3" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecognitionConfig) Reset()         { *m = RecognitionConfig{} }
func (m *RecognitionConfig) String() string { return proto.CompactTextString(m) }
func (*RecognitionConfig) ProtoMessage()    {}
func (*RecognitionConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{4}
}

func (m *RecognitionConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognitionConfig.Unmarshal(m, b)
}
func (m *RecognitionConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognitionConfig.Marshal(b, m, deterministic)
}
func (m *RecognitionConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognitionConfig.Merge(m, src)
}
func (m *RecognitionConfig) XXX_Size() int {
	return xxx_messageInfo_RecognitionConfig.Size(m)
}
func (m *RecognitionConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognitionConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RecognitionConfig proto.InternalMessageInfo

func (m *RecognitionConfig) GetEncoding() RecognitionConfig_AudioEncoding {
	if m != nil {
		return m.Encoding
	}
	return RecognitionConfig_ENCODING_UNSPECIFIED
}

func (m *RecognitionConfig) GetSampleRateHertz() int32 {
	if m != nil {
		return m.SampleRateHertz
	}
	return 0
}

func (m *RecognitionConfig) GetLanguageCode() string {
	if m != nil {
		return m.LanguageCode
	}
	return ""
}

func (m *RecognitionConfig) GetMaxAlternatives() int32 {
	if m != nil {
		return m.MaxAlternatives
	}
	return 0
}

func (m *RecognitionConfig) GetProfanityFilter() bool {
	if m != nil {
		return m.ProfanityFilter
	}
	return false
}

func (m *RecognitionConfig) GetSpeechContexts() []*SpeechContext {
	if m != nil {
		return m.SpeechContexts
	}
	return nil
}

func (m *RecognitionConfig) GetEnableWordTimeOffsets() bool {
	if m != nil {
		return m.EnableWordTimeOffsets
	}
	return false
}

func (m *RecognitionConfig) GetMetadata() *RecognitionMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *RecognitionConfig) GetDisableAutomaticPunctuation() bool {
	if m != nil {
		return m.DisableAutomaticPunctuation
	}
	return false
}

func (m *RecognitionConfig) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

// Description of audio data to be recognized.
type RecognitionMetadata struct {
	// The audio type that most closely describes the audio being recognized.
	MicrophoneDistance RecognitionMetadata_MicrophoneDistance `protobuf:"varint,4,opt,name=microphone_distance,json=microphoneDistance,proto3,enum=sogou.speech.asr.v1.RecognitionMetadata_MicrophoneDistance" json:"microphone_distance,omitempty"`
	// The name of device used to make the recording.
	RecordingDeviceName  string   `protobuf:"bytes,7,opt,name=recording_device_name,json=recordingDeviceName,proto3" json:"recording_device_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecognitionMetadata) Reset()         { *m = RecognitionMetadata{} }
func (m *RecognitionMetadata) String() string { return proto.CompactTextString(m) }
func (*RecognitionMetadata) ProtoMessage()    {}
func (*RecognitionMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{5}
}

func (m *RecognitionMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognitionMetadata.Unmarshal(m, b)
}
func (m *RecognitionMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognitionMetadata.Marshal(b, m, deterministic)
}
func (m *RecognitionMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognitionMetadata.Merge(m, src)
}
func (m *RecognitionMetadata) XXX_Size() int {
	return xxx_messageInfo_RecognitionMetadata.Size(m)
}
func (m *RecognitionMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognitionMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_RecognitionMetadata proto.InternalMessageInfo

func (m *RecognitionMetadata) GetMicrophoneDistance() RecognitionMetadata_MicrophoneDistance {
	if m != nil {
		return m.MicrophoneDistance
	}
	return RecognitionMetadata_MICROPHONE_DISTANCE_UNSPECIFIED
}

func (m *RecognitionMetadata) GetRecordingDeviceName() string {
	if m != nil {
		return m.RecordingDeviceName
	}
	return ""
}

// Provides "hints" to the speech recognizer to favor specific words and phrases
// in the results.
type SpeechContext struct {
	// *Optional* A list of strings containing words and phrases "hints" so that
	// the speech recognition is more likely to recognize them. This can be used
	// to improve the accuracy for specific words and phrases, for example, if
	// specific commands are typically spoken by the user. This can also be used
	// to add additional words to the vocabulary of the recognizer. See [usage limits]
	Phrases              []string `protobuf:"bytes,1,rep,name=phrases,proto3" json:"phrases,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpeechContext) Reset()         { *m = SpeechContext{} }
func (m *SpeechContext) String() string { return proto.CompactTextString(m) }
func (*SpeechContext) ProtoMessage()    {}
func (*SpeechContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{6}
}

func (m *SpeechContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpeechContext.Unmarshal(m, b)
}
func (m *SpeechContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpeechContext.Marshal(b, m, deterministic)
}
func (m *SpeechContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpeechContext.Merge(m, src)
}
func (m *SpeechContext) XXX_Size() int {
	return xxx_messageInfo_SpeechContext.Size(m)
}
func (m *SpeechContext) XXX_DiscardUnknown() {
	xxx_messageInfo_SpeechContext.DiscardUnknown(m)
}

var xxx_messageInfo_SpeechContext proto.InternalMessageInfo

func (m *SpeechContext) GetPhrases() []string {
	if m != nil {
		return m.Phrases
	}
	return nil
}

// Contains audio data in the encoding specified in the `RecognitionConfig`.
// Either `content` or `uri` must be supplied. Supplying both or neither
// returns [google.rpc.Code.INVALID_ARGUMENT].
type RecognitionAudio struct {
	// The audio source, which is either inline content or a uri.
	//
	// Types that are valid to be assigned to AudioSource:
	//	*RecognitionAudio_Content
	//	*RecognitionAudio_Uri
	AudioSource          isRecognitionAudio_AudioSource `protobuf_oneof:"audio_source"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *RecognitionAudio) Reset()         { *m = RecognitionAudio{} }
func (m *RecognitionAudio) String() string { return proto.CompactTextString(m) }
func (*RecognitionAudio) ProtoMessage()    {}
func (*RecognitionAudio) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{7}
}

func (m *RecognitionAudio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognitionAudio.Unmarshal(m, b)
}
func (m *RecognitionAudio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognitionAudio.Marshal(b, m, deterministic)
}
func (m *RecognitionAudio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognitionAudio.Merge(m, src)
}
func (m *RecognitionAudio) XXX_Size() int {
	return xxx_messageInfo_RecognitionAudio.Size(m)
}
func (m *RecognitionAudio) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognitionAudio.DiscardUnknown(m)
}

var xxx_messageInfo_RecognitionAudio proto.InternalMessageInfo

type isRecognitionAudio_AudioSource interface {
	isRecognitionAudio_AudioSource()
}

type RecognitionAudio_Content struct {
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3,oneof"`
}

type RecognitionAudio_Uri struct {
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3,oneof"`
}

func (*RecognitionAudio_Content) isRecognitionAudio_AudioSource() {}

func (*RecognitionAudio_Uri) isRecognitionAudio_AudioSource() {}

func (m *RecognitionAudio) GetAudioSource() isRecognitionAudio_AudioSource {
	if m != nil {
		return m.AudioSource
	}
	return nil
}

func (m *RecognitionAudio) GetContent() []byte {
	if x, ok := m.GetAudioSource().(*RecognitionAudio_Content); ok {
		return x.Content
	}
	return nil
}

func (m *RecognitionAudio) GetUri() string {
	if x, ok := m.GetAudioSource().(*RecognitionAudio_Uri); ok {
		return x.Uri
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RecognitionAudio) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RecognitionAudio_Content)(nil),
		(*RecognitionAudio_Uri)(nil),
	}
}

// The only message returned to the client by the `Recognize` method. It
// contains the result as zero or more sequential `SpeechRecognitionResult`
// messages.
type RecognizeResponse struct {
	// Output only. Sequential list of transcription results corresponding to
	// sequential portions of audio.
	Results              []*SpeechRecognitionResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RecognizeResponse) Reset()         { *m = RecognizeResponse{} }
func (m *RecognizeResponse) String() string { return proto.CompactTextString(m) }
func (*RecognizeResponse) ProtoMessage()    {}
func (*RecognizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{8}
}

func (m *RecognizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognizeResponse.Unmarshal(m, b)
}
func (m *RecognizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognizeResponse.Marshal(b, m, deterministic)
}
func (m *RecognizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognizeResponse.Merge(m, src)
}
func (m *RecognizeResponse) XXX_Size() int {
	return xxx_messageInfo_RecognizeResponse.Size(m)
}
func (m *RecognizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecognizeResponse proto.InternalMessageInfo

func (m *RecognizeResponse) GetResults() []*SpeechRecognitionResult {
	if m != nil {
		return m.Results
	}
	return nil
}

// The only message returned to the client by the `LongRunningRecognize` method.
// It contains the result as zero or more sequential `SpeechRecognitionResult`
// messages. It is included in the `result.response` field of the `Operation`
// returned by the `GetOperation` call of the `sogou.speech.longrunning.Operations`
// service.
type LongRunningRecognizeResponse struct {
	Results              []*SpeechRecognitionResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *LongRunningRecognizeResponse) Reset()         { *m = LongRunningRecognizeResponse{} }
func (m *LongRunningRecognizeResponse) String() string { return proto.CompactTextString(m) }
func (*LongRunningRecognizeResponse) ProtoMessage()    {}
func (*LongRunningRecognizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{9}
}

func (m *LongRunningRecognizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongRunningRecognizeResponse.Unmarshal(m, b)
}
func (m *LongRunningRecognizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongRunningRecognizeResponse.Marshal(b, m, deterministic)
}
func (m *LongRunningRecognizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongRunningRecognizeResponse.Merge(m, src)
}
func (m *LongRunningRecognizeResponse) XXX_Size() int {
	return xxx_messageInfo_LongRunningRecognizeResponse.Size(m)
}
func (m *LongRunningRecognizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LongRunningRecognizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LongRunningRecognizeResponse proto.InternalMessageInfo

func (m *LongRunningRecognizeResponse) GetResults() []*SpeechRecognitionResult {
	if m != nil {
		return m.Results
	}
	return nil
}

// Describes the progress of a long-running `LongRunningRecognize` call. It is
// included in the `metadata` field of the `Operation` returned by the
// `GetOperation` call of the `sogou.speech.longrunning.Operations` service.
type LongRunningRecognizeMetadata struct {
	// Approximate percentage of audio processed thus far. Guaranteed to be 100
	// when the audio is fully processed and the results are available.
	ProgressPercent int32 `protobuf:"varint,1,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	// Time when the request was received.
	StartTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Time of the most recent processing update.
	LastUpdateTime       *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LongRunningRecognizeMetadata) Reset()         { *m = LongRunningRecognizeMetadata{} }
func (m *LongRunningRecognizeMetadata) String() string { return proto.CompactTextString(m) }
func (*LongRunningRecognizeMetadata) ProtoMessage()    {}
func (*LongRunningRecognizeMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{10}
}

func (m *LongRunningRecognizeMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongRunningRecognizeMetadata.Unmarshal(m, b)
}
func (m *LongRunningRecognizeMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongRunningRecognizeMetadata.Marshal(b, m, deterministic)
}
func (m *LongRunningRecognizeMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongRunningRecognizeMetadata.Merge(m, src)
}
func (m *LongRunningRecognizeMetadata) XXX_Size() int {
	return xxx_messageInfo_LongRunningRecognizeMetadata.Size(m)
}
func (m *LongRunningRecognizeMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_LongRunningRecognizeMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_LongRunningRecognizeMetadata proto.InternalMessageInfo

func (m *LongRunningRecognizeMetadata) GetProgressPercent() int32 {
	if m != nil {
		return m.ProgressPercent
	}
	return 0
}

func (m *LongRunningRecognizeMetadata) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *LongRunningRecognizeMetadata) GetLastUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdateTime
	}
	return nil
}

// `StreamingRecognizeResponse` is the only message returned to the client by
// `StreamingRecognize`. A series of zero or more `StreamingRecognizeResponse`
// messages are streamed back to the client. If there is no recognizable
// audio, and `single_utterance` is set to false, then no messages are streamed
// back to the client.
// In each response, only one of these fields will be set:
//   `error`,
//   `speech_event_type`, or
//   one or more (repeated) `results`.
type StreamingRecognizeResponse struct {
	// *Output-only* If set, returns a [google.rpc.Status] message that
	// specifies the error for the operation.
	Error *status.Status `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// *Output-only* This repeated list contains zero or more results that
	// correspond to consecutive portions of the audio currently being processed.
	// It contains zero or more `is_final=false` results followed by zero or one
	// `is_final=true` result (the newly settled portion).
	Results []*StreamingRecognitionResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	// *Output-only* Indicates the type of speech event.
	SpeechEventType      StreamingRecognizeResponse_SpeechEventType `protobuf:"varint,4,opt,name=speech_event_type,json=speechEventType,proto3,enum=sogou.speech.asr.v1.StreamingRecognizeResponse_SpeechEventType" json:"speech_event_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *StreamingRecognizeResponse) Reset()         { *m = StreamingRecognizeResponse{} }
func (m *StreamingRecognizeResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingRecognizeResponse) ProtoMessage()    {}
func (*StreamingRecognizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{11}
}

func (m *StreamingRecognizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRecognizeResponse.Unmarshal(m, b)
}
func (m *StreamingRecognizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRecognizeResponse.Marshal(b, m, deterministic)
}
func (m *StreamingRecognizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRecognizeResponse.Merge(m, src)
}
func (m *StreamingRecognizeResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingRecognizeResponse.Size(m)
}
func (m *StreamingRecognizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRecognizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRecognizeResponse proto.InternalMessageInfo

func (m *StreamingRecognizeResponse) GetError() *status.Status {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *StreamingRecognizeResponse) GetResults() []*StreamingRecognitionResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *StreamingRecognizeResponse) GetSpeechEventType() StreamingRecognizeResponse_SpeechEventType {
	if m != nil {
		return m.SpeechEventType
	}
	return StreamingRecognizeResponse_SPEECH_EVENT_UNSPECIFIED
}

// A streaming speech recognition result corresponding to a portion of the audio
// that is currently being processed.
type StreamingRecognitionResult struct {
	// *Output-only* May contain one or more recognition hypotheses (up to the
	// maximum specified in `max_alternatives`).
	Alternatives []*SpeechRecognitionAlternative `protobuf:"bytes,1,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	// *Output-only* If `false`, this `StreamingRecognitionResult` represents an
	// interim result that may change. If `true`, this is the final time the
	// speech service will return this particular `StreamingRecognitionResult`,
	// the recognizer will not return any further hypotheses for this portion of
	// the transcript and corresponding audio.
	IsFinal bool `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// *Output-only* An estimate of the likelihood that the recognizer will not
	// change its guess about this interim result. Values range from 0.0
	// (completely unstable) to 1.0 (completely stable).
	// This field is only provided for interim results (`is_final=false`).
	// The default of 0.0 is a sentinel value indicating `stability` was not set.
	Stability            float32  `protobuf:"fixed32,3,opt,name=stability,proto3" json:"stability,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRecognitionResult) Reset()         { *m = StreamingRecognitionResult{} }
func (m *StreamingRecognitionResult) String() string { return proto.CompactTextString(m) }
func (*StreamingRecognitionResult) ProtoMessage()    {}
func (*StreamingRecognitionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{12}
}

func (m *StreamingRecognitionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRecognitionResult.Unmarshal(m, b)
}
func (m *StreamingRecognitionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRecognitionResult.Marshal(b, m, deterministic)
}
func (m *StreamingRecognitionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRecognitionResult.Merge(m, src)
}
func (m *StreamingRecognitionResult) XXX_Size() int {
	return xxx_messageInfo_StreamingRecognitionResult.Size(m)
}
func (m *StreamingRecognitionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRecognitionResult.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRecognitionResult proto.InternalMessageInfo

func (m *StreamingRecognitionResult) GetAlternatives() []*SpeechRecognitionAlternative {
	if m != nil {
		return m.Alternatives
	}
	return nil
}

func (m *StreamingRecognitionResult) GetIsFinal() bool {
	if m != nil {
		return m.IsFinal
	}
	return false
}

func (m *StreamingRecognitionResult) GetStability() float32 {
	if m != nil {
		return m.Stability
	}
	return 0
}

// A speech recognition result corresponding to a portion of the audio.
type SpeechRecognitionResult struct {
	// Output only. May contain one or more recognition hypotheses (up to the
	// maximum specified in `max_alternatives`).
	// These alternatives are ordered in terms of accuracy, with the top (first)
	// alternative being the most probable, as ranked by the recognizer.
	Alternatives         []*SpeechRecognitionAlternative `protobuf:"bytes,1,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *SpeechRecognitionResult) Reset()         { *m = SpeechRecognitionResult{} }
func (m *SpeechRecognitionResult) String() string { return proto.CompactTextString(m) }
func (*SpeechRecognitionResult) ProtoMessage()    {}
func (*SpeechRecognitionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{13}
}

func (m *SpeechRecognitionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpeechRecognitionResult.Unmarshal(m, b)
}
func (m *SpeechRecognitionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpeechRecognitionResult.Marshal(b, m, deterministic)
}
func (m *SpeechRecognitionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpeechRecognitionResult.Merge(m, src)
}
func (m *SpeechRecognitionResult) XXX_Size() int {
	return xxx_messageInfo_SpeechRecognitionResult.Size(m)
}
func (m *SpeechRecognitionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SpeechRecognitionResult.DiscardUnknown(m)
}

var xxx_messageInfo_SpeechRecognitionResult proto.InternalMessageInfo

func (m *SpeechRecognitionResult) GetAlternatives() []*SpeechRecognitionAlternative {
	if m != nil {
		return m.Alternatives
	}
	return nil
}

// Alternative hypotheses (a.k.a. n-best list).
type SpeechRecognitionAlternative struct {
	// *Output-only* Transcript text representing the words that the user spoke.
	Transcript string `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`
	// *Output-only* The confidence estimate between 0.0 and 1.0. A higher number
	// indicates an estimated greater likelihood that the recognized words are
	// correct. This field is typically provided only for the top hypothesis, and
	// only for `is_final=true` results. Clients should not rely on the
	// `confidence` field as it is not guaranteed to be accurate or consistent.
	// The default of 0.0 is a sentinel value indicating `confidence` was not set.
	Confidence float32 `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// *Output-only* A list of word-specific information for each recognized word.
	Words                []*WordInfo `protobuf:"bytes,3,rep,name=words,proto3" json:"words,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SpeechRecognitionAlternative) Reset()         { *m = SpeechRecognitionAlternative{} }
func (m *SpeechRecognitionAlternative) String() string { return proto.CompactTextString(m) }
func (*SpeechRecognitionAlternative) ProtoMessage()    {}
func (*SpeechRecognitionAlternative) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{14}
}

func (m *SpeechRecognitionAlternative) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpeechRecognitionAlternative.Unmarshal(m, b)
}
func (m *SpeechRecognitionAlternative) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpeechRecognitionAlternative.Marshal(b, m, deterministic)
}
func (m *SpeechRecognitionAlternative) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpeechRecognitionAlternative.Merge(m, src)
}
func (m *SpeechRecognitionAlternative) XXX_Size() int {
	return xxx_messageInfo_SpeechRecognitionAlternative.Size(m)
}
func (m *SpeechRecognitionAlternative) XXX_DiscardUnknown() {
	xxx_messageInfo_SpeechRecognitionAlternative.DiscardUnknown(m)
}

var xxx_messageInfo_SpeechRecognitionAlternative proto.InternalMessageInfo

func (m *SpeechRecognitionAlternative) GetTranscript() string {
	if m != nil {
		return m.Transcript
	}
	return ""
}

func (m *SpeechRecognitionAlternative) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

func (m *SpeechRecognitionAlternative) GetWords() []*WordInfo {
	if m != nil {
		return m.Words
	}
	return nil
}

// Word-specific information for recognized words. Word information is only
// included in the response when certain request parameters are set, such
// as `enable_word_time_offsets`.
type WordInfo struct {
	// *Output-only* Time offset relative to the beginning of the audio,
	// and corresponding to the start of the spoken word.
	// This field is only set if `enable_word_time_offsets=true` and only
	// in the top hypothesis.
	// This is an experimental feature and the accuracy of the time offset can
	// vary.
	StartTime *duration.Duration `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// *Output-only* Time offset relative to the beginning of the audio,
	// and corresponding to the end of the spoken word.
	// This field is only set if `enable_word_time_offsets=true` and only
	// in the top hypothesis.
	// This is an experimental feature and the accuracy of the time offset can
	// vary.
	EndTime *duration.Duration `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// *Output-only* The word corresponding to this set of information.
	Word                 string   `protobuf:"bytes,3,opt,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WordInfo) Reset()         { *m = WordInfo{} }
func (m *WordInfo) String() string { return proto.CompactTextString(m) }
func (*WordInfo) ProtoMessage()    {}
func (*WordInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a98b687a02867fc, []int{15}
}

func (m *WordInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WordInfo.Unmarshal(m, b)
}
func (m *WordInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WordInfo.Marshal(b, m, deterministic)
}
func (m *WordInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WordInfo.Merge(m, src)
}
func (m *WordInfo) XXX_Size() int {
	return xxx_messageInfo_WordInfo.Size(m)
}
func (m *WordInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WordInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WordInfo proto.InternalMessageInfo

func (m *WordInfo) GetStartTime() *duration.Duration {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *WordInfo) GetEndTime() *duration.Duration {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *WordInfo) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func init() {
	proto.RegisterEnum("sogou.speech.asr.v1.RecognitionConfig_AudioEncoding", RecognitionConfig_AudioEncoding_name, RecognitionConfig_AudioEncoding_value)
	proto.RegisterEnum("sogou.speech.asr.v1.RecognitionMetadata_MicrophoneDistance", RecognitionMetadata_MicrophoneDistance_name, RecognitionMetadata_MicrophoneDistance_value)
	proto.RegisterEnum("sogou.speech.asr.v1.StreamingRecognizeResponse_SpeechEventType", StreamingRecognizeResponse_SpeechEventType_name, StreamingRecognizeResponse_SpeechEventType_value)
	proto.RegisterType((*RecognizeRequest)(nil), "sogou.speech.asr.v1.RecognizeRequest")
	proto.RegisterType((*LongRunningRecognizeRequest)(nil), "sogou.speech.asr.v1.LongRunningRecognizeRequest")
	proto.RegisterType((*StreamingRecognizeRequest)(nil), "sogou.speech.asr.v1.StreamingRecognizeRequest")
	proto.RegisterType((*StreamingRecognitionConfig)(nil), "sogou.speech.asr.v1.StreamingRecognitionConfig")
	proto.RegisterType((*RecognitionConfig)(nil), "sogou.speech.asr.v1.RecognitionConfig")
	proto.RegisterType((*RecognitionMetadata)(nil), "sogou.speech.asr.v1.RecognitionMetadata")
	proto.RegisterType((*SpeechContext)(nil), "sogou.speech.asr.v1.SpeechContext")
	proto.RegisterType((*RecognitionAudio)(nil), "sogou.speech.asr.v1.RecognitionAudio")
	proto.RegisterType((*RecognizeResponse)(nil), "sogou.speech.asr.v1.RecognizeResponse")
	proto.RegisterType((*LongRunningRecognizeResponse)(nil), "sogou.speech.asr.v1.LongRunningRecognizeResponse")
	proto.RegisterType((*LongRunningRecognizeMetadata)(nil), "sogou.speech.asr.v1.LongRunningRecognizeMetadata")
	proto.RegisterType((*StreamingRecognizeResponse)(nil), "sogou.speech.asr.v1.StreamingRecognizeResponse")
	proto.RegisterType((*StreamingRecognitionResult)(nil), "sogou.speech.asr.v1.StreamingRecognitionResult")
	proto.RegisterType((*SpeechRecognitionResult)(nil), "sogou.speech.asr.v1.SpeechRecognitionResult")
	proto.RegisterType((*SpeechRecognitionAlternative)(nil), "sogou.speech.asr.v1.SpeechRecognitionAlternative")
	proto.RegisterType((*WordInfo)(nil), "sogou.speech.asr.v1.WordInfo")
}

func init() { proto.RegisterFile("sogou/speech/asr/v1/asr.proto", fileDescriptor_2a98b687a02867fc) }

var fileDescriptor_2a98b687a02867fc = []byte{
	// 1512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x4f, 0x6f, 0x1b, 0xc7,
	0x15, 0xf7, 0x92, 0xa6, 0x45, 0x3e, 0x4b, 0x22, 0x3d, 0x72, 0x60, 0x5a, 0x96, 0x63, 0x63, 0x8d,
	0x24, 0x72, 0x51, 0x90, 0x91, 0x12, 0xf4, 0x0f, 0x0c, 0xb4, 0xa0, 0xc8, 0xa5, 0x48, 0x44, 0x22,
	0x89, 0x21, 0xe5, 0x14, 0xa9, 0x80, 0xc5, 0x68, 0x77, 0x48, 0x2d, 0xca, 0xdd, 0xd9, 0xce, 0xcc,
	0xaa, 0x56, 0xbe, 0x41, 0x2f, 0xed, 0xa1, 0xb7, 0x5e, 0x0a, 0xf4, 0xd0, 0x43, 0x90, 0x6b, 0x2f,
	0xfd, 0x08, 0x69, 0x3f, 0x4e, 0x0f, 0x3d, 0x16, 0x33, 0xb3, 0x4b, 0x91, 0x14, 0x2d, 0xa9, 0x68,
	0x0b, 0xe4, 0x44, 0xce, 0xef, 0xfd, 0xde, 0x9b, 0x37, 0x6f, 0xde, 0x7b, 0xf3, 0x16, 0x9e, 0x0b,
	0x36, 0x61, 0x49, 0x5d, 0xc4, 0x94, 0x7a, 0xe7, 0x75, 0x22, 0x78, 0xfd, 0x62, 0x4f, 0xfd, 0xd4,
	0x62, 0xce, 0x24, 0x43, 0x5b, 0x5a, 0x5c, 0x33, 0xe2, 0x9a, 0xc2, 0x2f, 0xf6, 0xb6, 0x9f, 0x4e,
	0x18, 0x9b, 0x4c, 0x69, 0x5d, 0x53, 0xce, 0x92, 0x71, 0x9d, 0x44, 0x97, 0x86, 0xbf, 0xfd, 0xe1,
	0xb2, 0xc8, 0x4f, 0x38, 0x91, 0x01, 0x8b, 0x52, 0xf9, 0x8b, 0x65, 0xb9, 0x0c, 0x42, 0x2a, 0x24,
	0x09, 0xe3, 0x94, 0xf0, 0x24, 0x25, 0xf0, 0xd8, 0xab, 0x0b, 0x49, 0x64, 0x22, 0x52, 0xc1, 0xeb,
	0x05, 0x47, 0xa7, 0x2c, 0x9a, 0xf0, 0x24, 0x8a, 0x82, 0x68, 0x52, 0x67, 0x31, 0x35, 0x7b, 0xa4,
	0x54, 0xfb, 0xf7, 0x16, 0x54, 0x30, 0xf5, 0xd8, 0x24, 0x0a, 0xbe, 0xa6, 0x98, 0xfe, 0x3a, 0xa1,
	0x42, 0xa2, 0x9f, 0xc1, 0x03, 0x8f, 0x45, 0xe3, 0x60, 0x52, 0xb5, 0x5e, 0x5a, 0xbb, 0x0f, 0xf7,
	0x3f, 0xae, 0xad, 0x38, 0x5a, 0x2d, 0x55, 0x53, 0xd6, 0x9a, 0x9a, 0x8d, 0x53, 0x2d, 0xf4, 0x06,
	0x0a, 0x24, 0xf1, 0x03, 0x56, 0xcd, 0x69, 0xf5, 0x8f, 0x6e, 0x53, 0x6f, 0x28, 0x32, 0x36, 0x3a,
	0xf6, 0x1f, 0x2d, 0x78, 0x76, 0xc4, 0xa2, 0x09, 0x36, 0x2e, 0x7f, 0xbf, 0x9c, 0xfb, 0xab, 0x05,
	0x4f, 0x87, 0x92, 0x53, 0x12, 0xae, 0x72, 0xed, 0x14, 0x2a, 0x22, 0x13, 0xba, 0x0b, 0x4e, 0xd6,
	0x57, 0xee, 0xb2, 0x6c, 0xe9, 0xca, 0xdb, 0xce, 0x3d, 0x5c, 0x9e, 0x99, 0x32, 0x10, 0xfa, 0x08,
	0x36, 0xb4, 0x13, 0xca, 0xb2, 0xa4, 0x91, 0xd4, 0x07, 0x58, 0xef, 0xdc, 0xc3, 0xeb, 0x1a, 0x6e,
	0x1a, 0xf4, 0x60, 0x0b, 0x1e, 0x5d, 0x39, 0xc1, 0x8d, 0x67, 0xf6, 0x5f, 0x72, 0xb0, 0xfd, 0xfe,
	0xdd, 0xfe, 0xeb, 0x98, 0xbe, 0x86, 0x8a, 0x08, 0xa2, 0xc9, 0x94, 0xba, 0x89, 0x94, 0x94, 0x93,
	0xc8, 0xa3, 0xda, 0xbb, 0x22, 0x2e, 0x1b, 0xfc, 0x24, 0x83, 0xd1, 0x27, 0x50, 0x0e, 0x22, 0x49,
	0x79, 0x10, 0xba, 0x9c, 0x8a, 0x64, 0x2a, 0x45, 0x35, 0xaf, 0x99, 0x9b, 0x29, 0x8c, 0x0d, 0x8a,
	0xbe, 0x00, 0x9b, 0x46, 0xe4, 0x6c, 0x4a, 0xdd, 0x25, 0xbe, 0x1b, 0x27, 0x91, 0x27, 0x13, 0x9d,
	0xc6, 0xd5, 0xfb, 0x5a, 0xf7, 0x85, 0x61, 0x76, 0x17, 0x2c, 0x0c, 0xae, 0x68, 0x6a, 0xd7, 0x90,
	0xf2, 0xc9, 0xbc, 0x7f, 0x05, 0xb3, 0xab, 0x86, 0x67, 0xee, 0xd9, 0xdf, 0x14, 0xe0, 0xd1, 0xf5,
	0xf8, 0x0c, 0xa0, 0x48, 0x23, 0x8f, 0xf9, 0x41, 0x64, 0x22, 0xb4, 0xb9, 0xff, 0xf9, 0xdd, 0x22,
	0x54, 0xd3, 0xd9, 0xe3, 0xa4, 0xba, 0x78, 0x66, 0x05, 0xfd, 0x00, 0x1e, 0x09, 0x12, 0xc6, 0x53,
	0xea, 0x72, 0x22, 0xa9, 0x7b, 0x4e, 0xb9, 0xfc, 0x5a, 0x87, 0xac, 0x80, 0xcb, 0x46, 0x80, 0x89,
	0xa4, 0x1d, 0x05, 0xa3, 0x57, 0xb0, 0x31, 0x25, 0xd1, 0x24, 0x21, 0x13, 0xea, 0x7a, 0xcc, 0xa7,
	0x3a, 0x60, 0x25, 0xbc, 0x9e, 0x81, 0x4d, 0xe6, 0x53, 0x75, 0x05, 0x21, 0x79, 0xe7, 0x92, 0xa9,
	0xa4, 0x3c, 0x22, 0x32, 0xb8, 0xa0, 0x42, 0x07, 0xa7, 0x80, 0xcb, 0x21, 0x79, 0xd7, 0x98, 0x83,
	0x15, 0x35, 0xe6, 0x6c, 0x4c, 0xa2, 0x40, 0x5e, 0xba, 0xe3, 0x40, 0x89, 0xd2, 0x68, 0x94, 0x67,
	0x78, 0x5b, 0xc3, 0xe8, 0x0b, 0x28, 0x9b, 0x13, 0x9a, 0xa4, 0x7b, 0x27, 0x45, 0xf5, 0xc1, 0xcb,
	0xfc, 0xee, 0xc3, 0x7d, 0x7b, 0x75, 0x42, 0xeb, 0x55, 0xd3, 0x50, 0xf1, 0xa6, 0x98, 0x5f, 0x0a,
	0xf4, 0x63, 0xa8, 0xa6, 0x37, 0xfa, 0x1b, 0xc6, 0x7d, 0x57, 0xb5, 0x33, 0x97, 0x8d, 0xc7, 0x82,
	0x4a, 0x51, 0x2d, 0xea, 0xfd, 0x3f, 0x30, 0xf2, 0x2f, 0x19, 0xf7, 0x47, 0x41, 0x48, 0xfb, 0x46,
	0x88, 0x5a, 0x50, 0x0c, 0xa9, 0x24, 0x3e, 0x91, 0xa4, 0x5a, 0xd2, 0x09, 0xba, 0x7b, 0x5b, 0xf8,
	0x8f, 0x53, 0x3e, 0x9e, 0x69, 0xa2, 0x03, 0x78, 0xee, 0x07, 0x42, 0xef, 0x4f, 0x12, 0xc9, 0x42,
	0x22, 0x03, 0x6f, 0x21, 0x97, 0x1e, 0x6a, 0x1f, 0x9e, 0xa5, 0xa4, 0x46, 0xc6, 0x99, 0xcf, 0xa3,
	0xc7, 0x50, 0x08, 0x99, 0x4f, 0xa7, 0xd5, 0x0d, 0x7d, 0x05, 0x66, 0x61, 0x5f, 0xc0, 0xc6, 0xc2,
	0x3d, 0xa3, 0x2a, 0x3c, 0x76, 0x7a, 0xcd, 0x7e, 0xab, 0xdb, 0x3b, 0x74, 0x4f, 0x7a, 0xc3, 0x81,
	0xd3, 0xec, 0xb6, 0xbb, 0x4e, 0xab, 0x72, 0x0f, 0xad, 0x43, 0xf1, 0xa8, 0xdb, 0x73, 0x1a, 0x78,
	0xef, 0x47, 0x15, 0x0b, 0x15, 0xe1, 0x7e, 0xfb, 0xa8, 0xd1, 0xac, 0xe4, 0x14, 0xde, 0x3f, 0x3c,
	0x74, 0xfb, 0x83, 0x93, 0x61, 0xe5, 0x01, 0x7a, 0x0c, 0x15, 0xf5, 0xcf, 0xfd, 0xb2, 0x3b, 0xea,
	0xb8, 0x1d, 0xa7, 0xd1, 0x72, 0x70, 0x65, 0x0d, 0x95, 0xe1, 0xe1, 0xb0, 0x7f, 0xd8, 0x3f, 0x71,
	0x87, 0x03, 0xc7, 0xf9, 0x45, 0xc5, 0xb7, 0xff, 0x94, 0x83, 0xad, 0x15, 0x67, 0x46, 0x53, 0xd8,
	0x0a, 0x03, 0x8f, 0xb3, 0xf8, 0x9c, 0x45, 0xd4, 0xf5, 0x03, 0x21, 0x75, 0xc6, 0xdf, 0xd7, 0x99,
	0xfb, 0xe6, 0xae, 0xa1, 0xab, 0x1d, 0xcf, 0x6c, 0xb4, 0x52, 0x13, 0x18, 0x85, 0xd7, 0x30, 0xb4,
	0x0f, 0x1f, 0x70, 0xea, 0x31, 0xae, 0x4e, 0xee, 0xfa, 0xf4, 0x22, 0xf0, 0xa8, 0x1b, 0x91, 0x90,
	0x56, 0xd7, 0x74, 0x8c, 0xb6, 0x66, 0xc2, 0x96, 0x96, 0xf5, 0x48, 0x48, 0xed, 0x31, 0xa0, 0xeb,
	0xd6, 0xd1, 0x2b, 0x78, 0x71, 0xdc, 0x6d, 0xe2, 0xfe, 0xa0, 0xd3, 0xef, 0x39, 0x6e, 0xab, 0x3b,
	0x1c, 0x35, 0x7a, 0x4d, 0x67, 0x29, 0x82, 0x1b, 0x50, 0x52, 0xf1, 0x6b, 0x77, 0x9d, 0xa3, 0x56,
	0xc5, 0x47, 0x1b, 0x50, 0x3c, 0xee, 0xb6, 0xcc, 0xea, 0xdb, 0x9c, 0x5a, 0xb6, 0x33, 0xe1, 0x3f,
	0xf3, 0xf6, 0x6b, 0xd8, 0x58, 0xc8, 0x49, 0x54, 0x85, 0xb5, 0xf8, 0x9c, 0x13, 0x41, 0x45, 0xd5,
	0x7a, 0x99, 0xdf, 0x2d, 0xe1, 0x6c, 0x69, 0xe3, 0xd9, 0x43, 0x38, 0xeb, 0xfa, 0x68, 0x1b, 0xd6,
	0xb2, 0x66, 0x6b, 0xa5, 0xcd, 0x36, 0x03, 0x10, 0x82, 0x7c, 0xc2, 0x03, 0x5d, 0xb3, 0xa5, 0xce,
	0x3d, 0xac, 0x16, 0x07, 0x9b, 0x60, 0x7a, 0xb1, 0x2b, 0x58, 0xc2, 0x3d, 0x6a, 0xff, 0x72, 0xd6,
	0x4c, 0xd4, 0x23, 0x21, 0x62, 0x16, 0x09, 0x8a, 0xda, 0xb0, 0x96, 0x75, 0x3e, 0x4b, 0xd7, 0xd2,
	0x0f, 0x6f, 0xa8, 0xa5, 0x39, 0x97, 0x4c, 0x5b, 0xc3, 0x99, 0xb2, 0x3d, 0x86, 0x9d, 0xd5, 0xef,
	0xe4, 0xff, 0x78, 0x9f, 0xef, 0xac, 0xd5, 0x1b, 0xcd, 0xd2, 0xcd, 0xf4, 0x93, 0x09, 0xa7, 0x42,
	0xb8, 0x31, 0xe5, 0x5e, 0x16, 0xae, 0x82, 0xee, 0x27, 0x1a, 0x1f, 0x18, 0x18, 0xfd, 0x14, 0x40,
	0x48, 0xc2, 0xa5, 0x2e, 0xfe, 0xf4, 0x05, 0xde, 0xae, 0x99, 0x39, 0xa6, 0x96, 0x0d, 0x3a, 0xb5,
	0x51, 0x36, 0xe8, 0xe0, 0x92, 0x66, 0xab, 0x35, 0x6a, 0x41, 0x65, 0x4a, 0x84, 0x74, 0x93, 0xd8,
	0x57, 0x1d, 0x53, 0x1b, 0xc8, 0xdf, 0x6a, 0x60, 0x53, 0xe9, 0x9c, 0x68, 0x15, 0x05, 0xda, 0xff,
	0x58, 0xf1, 0x10, 0xce, 0xc5, 0x6c, 0x17, 0x0a, 0x94, 0x73, 0xc6, 0xd3, 0x77, 0x10, 0x65, 0x96,
	0x79, 0xec, 0xd5, 0x86, 0x7a, 0xc4, 0xc2, 0x86, 0x80, 0xba, 0x57, 0xd1, 0xcd, 0xe9, 0xe8, 0xde,
	0xfd, 0x89, 0x5f, 0x0a, 0x30, 0xfa, 0x15, 0x3c, 0x4a, 0x9b, 0x2c, 0xbd, 0xa0, 0x91, 0x74, 0xe5,
	0x65, 0x9c, 0x15, 0xeb, 0xcf, 0xef, 0x64, 0xf4, 0xea, 0x00, 0xe9, 0x6d, 0x3a, 0xca, 0xce, 0xe8,
	0x32, 0xa6, 0x38, 0x6d, 0xdf, 0x33, 0xc0, 0x3e, 0x82, 0xf2, 0x12, 0x07, 0xed, 0x40, 0x55, 0x75,
	0x94, 0x66, 0xc7, 0x75, 0xde, 0x3a, 0xbd, 0xd1, 0x52, 0xbd, 0x3d, 0x83, 0x27, 0x4e, 0xaf, 0xe5,
	0xf6, 0xdb, 0xee, 0xb0, 0xdb, 0x3b, 0x3c, 0x72, 0xdc, 0x93, 0xd1, 0xc8, 0xc1, 0xaa, 0x30, 0x2b,
	0x96, 0xfd, 0xad, 0xb5, 0x7a, 0xae, 0x30, 0x47, 0x44, 0x27, 0xb0, 0xbe, 0xf0, 0x20, 0x99, 0x3c,
	0xdc, 0xbb, 0x5b, 0x1e, 0xce, 0xbd, 0x59, 0x78, 0xc1, 0x0c, 0x7a, 0x0a, 0xc5, 0x40, 0xb8, 0xe3,
	0x20, 0x22, 0xd3, 0x74, 0xcc, 0x58, 0x0b, 0x44, 0x5b, 0x2d, 0xd1, 0x0e, 0xa8, 0x94, 0x39, 0x0b,
	0xa6, 0x81, 0xbc, 0xd4, 0xe9, 0x91, 0xc3, 0x57, 0x80, 0x1d, 0xc3, 0x93, 0xf7, 0xa4, 0xfb, 0xff,
	0xc9, 0x55, 0xfb, 0x0f, 0x16, 0xec, 0xdc, 0x44, 0x47, 0x1f, 0x02, 0x48, 0x4e, 0x22, 0xe1, 0xf1,
	0x20, 0x36, 0x65, 0x53, 0xc2, 0x73, 0x88, 0x92, 0xeb, 0x21, 0xcb, 0xa7, 0xd9, 0x50, 0x95, 0xc3,
	0x73, 0x08, 0xfa, 0x0c, 0x0a, 0xea, 0x35, 0x55, 0x53, 0x94, 0x72, 0xf8, 0xf9, 0x4a, 0x87, 0xd5,
	0x83, 0xda, 0x8d, 0xc6, 0x0c, 0x1b, 0xae, 0xfd, 0x3b, 0x0b, 0x8a, 0x19, 0x86, 0x7e, 0xb2, 0x50,
	0x93, 0x26, 0xf1, 0x9f, 0x5e, 0x2b, 0xa9, 0x56, 0xfa, 0x71, 0x32, 0x5f, 0x92, 0x9f, 0xab, 0xb1,
	0xc8, 0x9f, 0xaf, 0xe5, 0x1b, 0xf4, 0xd6, 0x68, 0xa4, 0x1f, 0x75, 0x84, 0xe0, 0xbe, 0xf2, 0x22,
	0x9d, 0x62, 0xf4, 0xff, 0xfd, 0xbf, 0xe7, 0x20, 0x4f, 0x04, 0x47, 0x5f, 0x41, 0x69, 0x96, 0xd3,
	0xe8, 0xc6, 0xd1, 0x7c, 0x36, 0x75, 0x6f, 0x7f, 0x7c, 0x1b, 0x2d, 0xad, 0xed, 0x10, 0x1e, 0xaf,
	0x6a, 0x63, 0xe8, 0xd3, 0x95, 0xfa, 0x37, 0x7c, 0x82, 0x6c, 0xbf, 0x5a, 0xd4, 0x98, 0xfb, 0xc0,
	0xaa, 0xf5, 0xb3, 0x0f, 0x2c, 0x74, 0x09, 0xe8, 0x7a, 0x9d, 0xa2, 0xda, 0x9d, 0x0b, 0xda, 0x6c,
	0x55, 0xff, 0x0f, 0x1b, 0xc0, 0xae, 0xf5, 0xa9, 0x75, 0xf0, 0x5b, 0x0b, 0x9e, 0x78, 0x2c, 0x5c,
	0xa5, 0x7a, 0x50, 0x6c, 0x08, 0x3e, 0x50, 0x97, 0x33, 0xb0, 0xbe, 0xfa, 0x64, 0xc2, 0xd4, 0x0c,
	0x99, 0x31, 0x0c, 0xdd, 0x63, 0x61, 0x9d, 0xc4, 0x81, 0x48, 0x3f, 0x70, 0xdf, 0x10, 0xc1, 0xff,
	0x65, 0x59, 0x7f, 0xce, 0xe5, 0x87, 0x83, 0x83, 0x6f, 0x72, 0x5b, 0x43, 0x4d, 0x32, 0x29, 0x5d,
	0x6b, 0x08, 0x5e, 0x7b, 0xbb, 0xf7, 0x37, 0x2d, 0xfb, 0x2e, 0x95, 0x9d, 0x1a, 0xd9, 0x69, 0x43,
	0xf0, 0xd3, 0xb7, 0x7b, 0x67, 0x0f, 0x74, 0x26, 0x7c, 0xf6, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xb4, 0x89, 0xa4, 0x85, 0x3d, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AsrClient is the client API for Asr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AsrClient interface {
	// Performs synchronous speech recognition: receive results after all audio
	// has been sent and processed.
	Recognize(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognizeResponse, error)
	// Performs asynchronous speech recognition: receive results via sogou.speech.longrunning.GetOperation interface
	LongRunningRecognize(ctx context.Context, in *LongRunningRecognizeRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// Performs bidirectional streaming speech recognition: receive results while
	// sending audio. This method is only available via the gRPC API (not REST).
	StreamingRecognize(ctx context.Context, opts ...grpc.CallOption) (Asr_StreamingRecognizeClient, error)
}

type asrClient struct {
	cc *grpc.ClientConn
}

func NewAsrClient(cc *grpc.ClientConn) AsrClient {
	return &asrClient{cc}
}

func (c *asrClient) Recognize(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognizeResponse, error) {
	out := new(RecognizeResponse)
	err := c.cc.Invoke(ctx, "/sogou.speech.asr.v1.asr/Recognize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asrClient) LongRunningRecognize(ctx context.Context, in *LongRunningRecognizeRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/sogou.speech.asr.v1.asr/LongRunningRecognize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asrClient) StreamingRecognize(ctx context.Context, opts ...grpc.CallOption) (Asr_StreamingRecognizeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Asr_serviceDesc.Streams[0], "/sogou.speech.asr.v1.asr/StreamingRecognize", opts...)
	if err != nil {
		return nil, err
	}
	x := &asrStreamingRecognizeClient{stream}
	return x, nil
}

type Asr_StreamingRecognizeClient interface {
	Send(*StreamingRecognizeRequest) error
	Recv() (*StreamingRecognizeResponse, error)
	grpc.ClientStream
}

type asrStreamingRecognizeClient struct {
	grpc.ClientStream
}

func (x *asrStreamingRecognizeClient) Send(m *StreamingRecognizeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *asrStreamingRecognizeClient) Recv() (*StreamingRecognizeResponse, error) {
	m := new(StreamingRecognizeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AsrServer is the server API for Asr service.
type AsrServer interface {
	// Performs synchronous speech recognition: receive results after all audio
	// has been sent and processed.
	Recognize(context.Context, *RecognizeRequest) (*RecognizeResponse, error)
	// Performs asynchronous speech recognition: receive results via sogou.speech.longrunning.GetOperation interface
	LongRunningRecognize(context.Context, *LongRunningRecognizeRequest) (*longrunning.Operation, error)
	// Performs bidirectional streaming speech recognition: receive results while
	// sending audio. This method is only available via the gRPC API (not REST).
	StreamingRecognize(Asr_StreamingRecognizeServer) error
}

// UnimplementedAsrServer can be embedded to have forward compatible implementations.
type UnimplementedAsrServer struct {
}

func (*UnimplementedAsrServer) Recognize(ctx context.Context, req *RecognizeRequest) (*RecognizeResponse, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method Recognize not implemented")
}
func (*UnimplementedAsrServer) LongRunningRecognize(ctx context.Context, req *LongRunningRecognizeRequest) (*longrunning.Operation, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method LongRunningRecognize not implemented")
}
func (*UnimplementedAsrServer) StreamingRecognize(srv Asr_StreamingRecognizeServer) error {
	return status1.Errorf(codes.Unimplemented, "method StreamingRecognize not implemented")
}

func RegisterAsrServer(s *grpc.Server, srv AsrServer) {
	s.RegisterService(&_Asr_serviceDesc, srv)
}

func _Asr_Recognize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecognizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsrServer).Recognize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sogou.speech.asr.v1.asr/Recognize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsrServer).Recognize(ctx, req.(*RecognizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asr_LongRunningRecognize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LongRunningRecognizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsrServer).LongRunningRecognize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sogou.speech.asr.v1.asr/LongRunningRecognize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsrServer).LongRunningRecognize(ctx, req.(*LongRunningRecognizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asr_StreamingRecognize_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AsrServer).StreamingRecognize(&asrStreamingRecognizeServer{stream})
}

type Asr_StreamingRecognizeServer interface {
	Send(*StreamingRecognizeResponse) error
	Recv() (*StreamingRecognizeRequest, error)
	grpc.ServerStream
}

type asrStreamingRecognizeServer struct {
	grpc.ServerStream
}

func (x *asrStreamingRecognizeServer) Send(m *StreamingRecognizeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *asrStreamingRecognizeServer) Recv() (*StreamingRecognizeRequest, error) {
	m := new(StreamingRecognizeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Asr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sogou.speech.asr.v1.asr",
	HandlerType: (*AsrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recognize",
			Handler:    _Asr_Recognize_Handler,
		},
		{
			MethodName: "LongRunningRecognize",
			Handler:    _Asr_LongRunningRecognize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingRecognize",
			Handler:       _Asr_StreamingRecognize_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sogou/speech/asr/v1/asr.proto",
}
