// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sogou/speech/mt/v1/mt.proto

package mt

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TranslateTextRequest struct {
	// *Required* The translate configurations
	Config *TranslateConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// *Required* The text will be translated
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranslateTextRequest) Reset()         { *m = TranslateTextRequest{} }
func (m *TranslateTextRequest) String() string { return proto.CompactTextString(m) }
func (*TranslateTextRequest) ProtoMessage()    {}
func (*TranslateTextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf95b1d8a9377ec9, []int{0}
}

func (m *TranslateTextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateTextRequest.Unmarshal(m, b)
}
func (m *TranslateTextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateTextRequest.Marshal(b, m, deterministic)
}
func (m *TranslateTextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateTextRequest.Merge(m, src)
}
func (m *TranslateTextRequest) XXX_Size() int {
	return xxx_messageInfo_TranslateTextRequest.Size(m)
}
func (m *TranslateTextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateTextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateTextRequest proto.InternalMessageInfo

func (m *TranslateTextRequest) GetConfig() *TranslateConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *TranslateTextRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type TranslateConfig struct {
	// *Required* The language code of the source text,
	// set to one of the language codes listed in [Language Support](https://zhiyin.sogou.com/doc/?url=/docs/content/mt/concepts/lauguages/).
	// Example: "zh-cmn-Hans-CN".
	SourceLanguageCode string `protobuf:"bytes,1,opt,name=source_language_code,json=sourceLanguageCode,proto3" json:"source_language_code,omitempty"`
	// *Required* The language code of the target text
	TargetLanguageCode   string   `protobuf:"bytes,2,opt,name=target_language_code,json=targetLanguageCode,proto3" json:"target_language_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranslateConfig) Reset()         { *m = TranslateConfig{} }
func (m *TranslateConfig) String() string { return proto.CompactTextString(m) }
func (*TranslateConfig) ProtoMessage()    {}
func (*TranslateConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf95b1d8a9377ec9, []int{1}
}

func (m *TranslateConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateConfig.Unmarshal(m, b)
}
func (m *TranslateConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateConfig.Marshal(b, m, deterministic)
}
func (m *TranslateConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateConfig.Merge(m, src)
}
func (m *TranslateConfig) XXX_Size() int {
	return xxx_messageInfo_TranslateConfig.Size(m)
}
func (m *TranslateConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateConfig proto.InternalMessageInfo

func (m *TranslateConfig) GetSourceLanguageCode() string {
	if m != nil {
		return m.SourceLanguageCode
	}
	return ""
}

func (m *TranslateConfig) GetTargetLanguageCode() string {
	if m != nil {
		return m.TargetLanguageCode
	}
	return ""
}

type TranslateTextResponse struct {
	// Source text
	SourceText string `protobuf:"bytes,1,opt,name=source_text,json=sourceText,proto3" json:"source_text,omitempty"`
	// Text translated into the target language.
	TranslatedText string `protobuf:"bytes,2,opt,name=translated_text,json=translatedText,proto3" json:"translated_text,omitempty"`
	// The language code of the source text
	SourceLanguageCode string `protobuf:"bytes,3,opt,name=source_language_code,json=sourceLanguageCode,proto3" json:"source_language_code,omitempty"`
	// The language code of the target text
	TargetLanguageCode   string   `protobuf:"bytes,4,opt,name=target_language_code,json=targetLanguageCode,proto3" json:"target_language_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranslateTextResponse) Reset()         { *m = TranslateTextResponse{} }
func (m *TranslateTextResponse) String() string { return proto.CompactTextString(m) }
func (*TranslateTextResponse) ProtoMessage()    {}
func (*TranslateTextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf95b1d8a9377ec9, []int{2}
}

func (m *TranslateTextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateTextResponse.Unmarshal(m, b)
}
func (m *TranslateTextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateTextResponse.Marshal(b, m, deterministic)
}
func (m *TranslateTextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateTextResponse.Merge(m, src)
}
func (m *TranslateTextResponse) XXX_Size() int {
	return xxx_messageInfo_TranslateTextResponse.Size(m)
}
func (m *TranslateTextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateTextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateTextResponse proto.InternalMessageInfo

func (m *TranslateTextResponse) GetSourceText() string {
	if m != nil {
		return m.SourceText
	}
	return ""
}

func (m *TranslateTextResponse) GetTranslatedText() string {
	if m != nil {
		return m.TranslatedText
	}
	return ""
}

func (m *TranslateTextResponse) GetSourceLanguageCode() string {
	if m != nil {
		return m.SourceLanguageCode
	}
	return ""
}

func (m *TranslateTextResponse) GetTargetLanguageCode() string {
	if m != nil {
		return m.TargetLanguageCode
	}
	return ""
}

func init() {
	proto.RegisterType((*TranslateTextRequest)(nil), "sogou.speech.mt.v1.TranslateTextRequest")
	proto.RegisterType((*TranslateConfig)(nil), "sogou.speech.mt.v1.TranslateConfig")
	proto.RegisterType((*TranslateTextResponse)(nil), "sogou.speech.mt.v1.TranslateTextResponse")
}

func init() { proto.RegisterFile("sogou/speech/mt/v1/mt.proto", fileDescriptor_cf95b1d8a9377ec9) }

var fileDescriptor_cf95b1d8a9377ec9 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4f, 0xf2, 0x30,
	0x18, 0xc7, 0xd3, 0x41, 0x78, 0x43, 0xc9, 0x2b, 0x49, 0x83, 0x86, 0xe8, 0x41, 0x82, 0x31, 0xe2,
	0xa5, 0x73, 0x78, 0xe4, 0x06, 0x57, 0x49, 0xc8, 0x58, 0x38, 0x18, 0x12, 0x32, 0xb7, 0x5a, 0x31,
	0x74, 0x9d, 0xeb, 0x33, 0xc2, 0xdd, 0x6f, 0xe2, 0xd1, 0x8f, 0xe0, 0xdd, 0x8b, 0x9f, 0xc8, 0xa3,
	0x59, 0x3b, 0x14, 0xa7, 0x18, 0xbd, 0x2d, 0xfd, 0xfd, 0x7f, 0x79, 0xfa, 0x5f, 0x1f, 0x7c, 0xa0,
	0x24, 0x97, 0xa9, 0xad, 0x62, 0xc6, 0x82, 0x1b, 0x5b, 0x80, 0xbd, 0x74, 0x6c, 0x01, 0x34, 0x4e,
	0x24, 0x48, 0x42, 0x34, 0xa4, 0x06, 0x52, 0x01, 0x74, 0xe9, 0xb4, 0x39, 0x6e, 0x78, 0x89, 0x1f,
	0xa9, 0x85, 0x0f, 0xcc, 0x63, 0x2b, 0x70, 0xd9, 0x5d, 0xca, 0x14, 0x90, 0x1e, 0xae, 0x04, 0x32,
	0xba, 0x9e, 0xf3, 0x26, 0x6a, 0xa1, 0x4e, 0xad, 0x7b, 0x44, 0xbf, 0xca, 0xf4, 0xdd, 0x1c, 0xe8,
	0xa8, 0x9b, 0x2b, 0x84, 0xe0, 0x32, 0xb0, 0x15, 0x34, 0xad, 0x16, 0xea, 0x54, 0x5d, 0xfd, 0xdd,
	0x4e, 0x71, 0xbd, 0x10, 0x27, 0x67, 0xb8, 0xa1, 0x64, 0x9a, 0x04, 0x6c, 0xb6, 0xf0, 0x23, 0x9e,
	0xfa, 0x9c, 0xcd, 0x02, 0x19, 0x32, 0x3d, 0xb1, 0xea, 0x12, 0xc3, 0x2e, 0x72, 0x34, 0x90, 0x21,
	0xcb, 0x0c, 0xf0, 0x13, 0xce, 0xa0, 0x60, 0x98, 0x41, 0xc4, 0xb0, 0x4d, 0xa3, 0xfd, 0x8c, 0xf0,
	0x6e, 0xa1, 0xa0, 0x8a, 0x65, 0xa4, 0x18, 0x39, 0xc4, 0xb5, 0x7c, 0xba, 0xbe, 0xab, 0x19, 0x8a,
	0xcd, 0x51, 0x16, 0x24, 0x27, 0xb8, 0x0e, 0x6b, 0x33, 0x9c, 0x6d, 0x14, 0xda, 0xf9, 0x38, 0xd6,
	0xc1, 0x6d, 0x3d, 0x4a, 0x7f, 0xee, 0x51, 0xde, 0xd6, 0xa3, 0x7b, 0x8b, 0x2d, 0x01, 0x24, 0xc4,
	0xff, 0x3f, 0x95, 0x21, 0x9d, 0x1f, 0x9f, 0x65, 0xe3, 0x41, 0xf7, 0x4f, 0x7f, 0x91, 0x34, 0x7f,
	0xa6, 0x7f, 0x8f, 0xf0, 0x5e, 0x20, 0xc5, 0x37, 0x42, 0xff, 0xdf, 0xd0, 0x1b, 0x65, 0xbb, 0x34,
	0x42, 0x97, 0xc7, 0x5c, 0x66, 0x97, 0x5f, 0x73, 0x13, 0x0e, 0xa4, 0xb0, 0xfd, 0x78, 0xae, 0xcc,
	0xea, 0xf5, 0x04, 0xbc, 0x22, 0xf4, 0x60, 0x95, 0xc6, 0xa3, 0xfe, 0xa3, 0x45, 0xc6, 0x3a, 0x32,
	0x36, 0xf9, 0xa1, 0x47, 0x27, 0xce, 0x93, 0x46, 0x2f, 0x39, 0x9a, 0x1a, 0x34, 0x1d, 0x7a, 0xd3,
	0x89, 0x73, 0x55, 0xd1, 0x4b, 0x7b, 0xfe, 0x16, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x10, 0x08, 0x93,
	0xd3, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MtClient is the client API for Mt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MtClient interface {
	TranslateText(ctx context.Context, in *TranslateTextRequest, opts ...grpc.CallOption) (*TranslateTextResponse, error)
}

type mtClient struct {
	cc *grpc.ClientConn
}

func NewMtClient(cc *grpc.ClientConn) MtClient {
	return &mtClient{cc}
}

func (c *mtClient) TranslateText(ctx context.Context, in *TranslateTextRequest, opts ...grpc.CallOption) (*TranslateTextResponse, error) {
	out := new(TranslateTextResponse)
	err := c.cc.Invoke(ctx, "/sogou.speech.mt.v1.mt/TranslateText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MtServer is the server API for Mt service.
type MtServer interface {
	TranslateText(context.Context, *TranslateTextRequest) (*TranslateTextResponse, error)
}

// UnimplementedMtServer can be embedded to have forward compatible implementations.
type UnimplementedMtServer struct {
}

func (*UnimplementedMtServer) TranslateText(ctx context.Context, req *TranslateTextRequest) (*TranslateTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TranslateText not implemented")
}

func RegisterMtServer(s *grpc.Server, srv MtServer) {
	s.RegisterService(&_Mt_serviceDesc, srv)
}

func _Mt_TranslateText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MtServer).TranslateText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sogou.speech.mt.v1.mt/TranslateText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MtServer).TranslateText(ctx, req.(*TranslateTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sogou.speech.mt.v1.mt",
	HandlerType: (*MtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TranslateText",
			Handler:    _Mt_TranslateText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sogou/speech/mt/v1/mt.proto",
}
